<?php
/*
 * Generated by WebUtil package
 * http://pear.oops.org/docs/li_WebAPI.html
 *
 * Copyright (c) 2018 JoungKyun.Kim <http://oops.org>
 */
switch ($file) {
	case 'ez' :
		$mime = 'application/andrew-inset';
		break;
	case 'atom' :
		$mime = 'application/atom+xml';
		break;
	case 'atomcat' :
		$mime = 'application/atomcat+xml';
		break;
	case 'atomsvc' :
		$mime = 'application/atomsvc+xml';
		break;
	case 'apxml' :
		$mime = 'application/auth-policy+xml';
		break;
	case 'ccxml' :
		$mime = 'application/ccxml+xml';
		break;
	case 'cellml' :
	case 'cml' :
		$mime = 'application/cellml+xml';
		break;
	case 'cpl' :
		$mime = 'application/cpl+xml';
		break;
	case 'davmount' :
		$mime = 'application/davmount+xml';
		break;
	case 'dcm' :
		$mime = 'application/dicom';
		break;
	case 'dssc' :
		$mime = 'application/dssc+der';
		break;
	case 'xdssc' :
		$mime = 'application/dssc+xml';
		break;
	case 'dvc' :
		$mime = 'application/dvcs';
		break;
	case 'emma' :
		$mime = 'application/emma+xml';
		break;
	case 'finf' :
		$mime = 'application/fastinfoset';
		break;
	case 'pfr' :
		$mime = 'application/font-tdpfr';
		break;
	case 'stk' :
		$mime = 'application/hyperstudio';
		break;
	case 'ipfix' :
		$mime = 'application/ipfix';
		break;
	case 'json' :
		$mime = 'application/json';
		break;
	case 'lostxml' :
		$mime = 'application/lost+xml';
		break;
	case 'hqx' :
		$mime = 'application/mac-binhex40';
		break;
	case 'mrc' :
		$mime = 'application/marc';
		break;
	case 'nb' :
	case 'ma' :
	case 'mb' :
		$mime = 'application/mathematica';
		break;
	case 'mbox' :
		$mime = 'application/mbox';
		break;
	case 'm21' :
	case 'mp21' :
		$mime = 'application/mp21';
		break;
	case 'doc' :
		$mime = 'application/msword';
		break;
	case 'mxf' :
		$mime = 'application/mxf';
		break;
	case 'orq' :
		$mime = 'application/ocsp-request';
		break;
	case 'ors' :
		$mime = 'application/ocsp-response';
		break;
	case 'bin' :
	case 'lha' :
	case 'lzh' :
	case 'exe' :
	case 'class' :
	case 'so' :
	case 'dll' :
	case 'img' :
	case 'iso' :
	case 'pyc' :
		$mime = 'application/octet-stream';
		break;
	case 'oda' :
		$mime = 'application/oda';
		break;
	case 'opf' :
		$mime = 'application/oebps-package+xml';
		break;
	case 'ogx' :
		$mime = 'application/ogg';
		break;
	case 'pdf' :
		$mime = 'application/pdf';
		break;
	case 'sig' :
		$mime = 'application/pgp-signature';
		break;
	case 'p10' :
		$mime = 'application/pkcs10';
		break;
	case 'p7m' :
	case 'p7c' :
		$mime = 'application/pkcs7-mime';
		break;
	case 'p7s' :
		$mime = 'application/pkcs7-signature';
		break;
	case 'cer' :
		$mime = 'application/pkix-cert';
		break;
	case 'crl' :
		$mime = 'application/pkix-crl';
		break;
	case 'pkipath' :
		$mime = 'application/pkix-pkipath';
		break;
	case 'pls' :
		$mime = 'application/pls+xml';
		break;
	case 'ai' :
	case 'eps' :
	case 'ps' :
		$mime = 'application/postscript';
		break;
	case 'cw' :
	case 'cww' :
		$mime = 'application/prs.cww';
		break;
	case 'rnd' :
	case 'rct' :
		$mime = 'application/prs.nprend';
		break;
	case 'rdf' :
		$mime = 'application/rdf+xml';
		break;
	case 'rif' :
		$mime = 'application/reginfo+xml';
		break;
	case 'rnc' :
		$mime = 'application/relax-ng-compact-syntax';
		break;
	case 'rld' :
		$mime = 'application/resource-lists-diff+xml';
		break;
	case 'rl' :
		$mime = 'application/resource-lists+xml';
		break;
	case 'rs' :
		$mime = 'application/rls-services+xml';
		break;
	case 'rtf' :
		$mime = 'application/rtf';
		break;
	case 'scq' :
		$mime = 'application/scvp-cv-request';
		break;
	case 'scs' :
		$mime = 'application/scvp-cv-response';
		break;
	case 'spq' :
		$mime = 'application/scvp-vp-request';
		break;
	case 'spp' :
		$mime = 'application/scvp-vp-response';
		break;
	case 'sdp' :
		$mime = 'application/sdp';
		break;
	case 'soc' :
		$mime = 'application/sgml-open-catalog';
		break;
	case 'shf' :
		$mime = 'application/shf+xml';
		break;
	case 'siv' :
	case 'sieve' :
		$mime = 'application/sieve';
		break;
	case 'cl' :
		$mime = 'application/simple-filter+xml';
		break;
	case 'smil' :
	case 'smi' :
	case 'sml' :
		$mime = 'application/smil';
		break;
	case 'rq' :
		$mime = 'application/sparql-query';
		break;
	case 'srx' :
		$mime = 'application/sparql-results+xml';
		break;
	case 'gram' :
		$mime = 'application/srgs';
		break;
	case 'grxml' :
		$mime = 'application/srgs+xml';
		break;
	case 'ssml' :
		$mime = 'application/ssml+xml';
		break;
	case 'tsq' :
		$mime = 'application/timestamp-query';
		break;
	case 'tsr' :
		$mime = 'application/timestamp-reply';
		break;
	case 'plb' :
		$mime = 'application/vnd.3gpp.pic-bw-large';
		break;
	case 'psb' :
		$mime = 'application/vnd.3gpp.pic-bw-small';
		break;
	case 'pvb' :
		$mime = 'application/vnd.3gpp.pic-bw-var';
		break;
	case 'sms' :
		$mime = 'application/vnd.3gpp2.sms';
		break;
	case 'tcap' :
		$mime = 'application/vnd.3gpp2.tcap';
		break;
	case 'pwn' :
		$mime = 'application/vnd.3M.Post-it-Notes';
		break;
	case 'aso' :
		$mime = 'application/vnd.accpac.simply.aso';
		break;
	case 'imp' :
		$mime = 'application/vnd.accpac.simply.imp';
		break;
	case 'acu' :
		$mime = 'application/vnd.acucobol';
		break;
	case 'atc' :
	case 'acutc' :
		$mime = 'application/vnd.acucorp';
		break;
	case 'xdp' :
		$mime = 'application/vnd.adobe.xdp+xml';
		break;
	case 'xfdf' :
		$mime = 'application/vnd.adobe.xfdf';
		break;
	case 'azf' :
		$mime = 'application/vnd.airzip.filesecure.azf';
		break;
	case 'azs' :
		$mime = 'application/vnd.airzip.filesecure.azs';
		break;
	case 'acc' :
		$mime = 'application/vnd.americandynamics.acc';
		break;
	case 'ami' :
		$mime = 'application/vnd.amiga.ami';
		break;
	case 'cii' :
		$mime = 'application/vnd.anser-web-certificate-issue-initiation';
		break;
	case 'fti' :
		$mime = 'application/vnd.anser-web-funds-transfer-initiation';
		break;
	case 'dist' :
	case 'distz' :
	case 'pkg' :
	case 'mpkg' :
		$mime = 'application/vnd.apple.installer+xml';
		break;
	case 'm3u8' :
		$mime = 'application/vnd.apple.mpegurl';
		break;
	case 'swi' :
		$mime = 'application/vnd.aristanetworks.swi';
		break;
	case 'aep' :
		$mime = 'application/vnd.audiograph';
		break;
	case 'package' :
		$mime = 'application/vnd.autopackage';
		break;
	case 'mpm' :
		$mime = 'application/vnd.blueice.multipass';
		break;
	case 'ep' :
		$mime = 'application/vnd.bluetooth.ep.oob';
		break;
	case 'bmi' :
		$mime = 'application/vnd.bmi';
		break;
	case 'rep' :
		$mime = 'application/vnd.businessobjects';
		break;
	case 'tlclient' :
		$mime = 'application/vnd.cendio.thinlinc.clientconf';
		break;
	case 'cdxml' :
		$mime = 'application/vnd.chemdraw+xml';
		break;
	case 'mmd' :
		$mime = 'application/vnd.chipnuts.karaoke-mmd';
		break;
	case 'cdy' :
		$mime = 'application/vnd.cinderella';
		break;
	case 'cla' :
		$mime = 'application/vnd.claymore';
		break;
	case 'rp9' :
		$mime = 'application/vnd.cloanto.rp9';
		break;
	case 'c4g' :
	case 'c4d' :
	case 'c4f' :
	case 'c4p' :
	case 'c4u' :
		$mime = 'application/vnd.clonk.c4group';
		break;
	case 'ica' :
	case 'icf' :
	case 'icd' :
	case 'ic0' :
	case 'ic1' :
	case 'ic2' :
	case 'ic3' :
	case 'ic4' :
	case 'ic5' :
	case 'ic6' :
	case 'ic7' :
	case 'ic8' :
		$mime = 'application/vnd.commerce-battelle';
		break;
	case 'csp' :
	case 'cst' :
		$mime = 'application/vnd.commonspace';
		break;
	case 'cdbcmsg' :
		$mime = 'application/vnd.contact.cmsg';
		break;
	case 'cmc' :
		$mime = 'application/vnd.cosmocaller';
		break;
	case 'clkx' :
		$mime = 'application/vnd.crick.clicker';
		break;
	case 'clkk' :
		$mime = 'application/vnd.crick.clicker.keyboard';
		break;
	case 'clkp' :
		$mime = 'application/vnd.crick.clicker.palette';
		break;
	case 'clkt' :
		$mime = 'application/vnd.crick.clicker.template';
		break;
	case 'clkw' :
		$mime = 'application/vnd.crick.clicker.wordbank';
		break;
	case 'wbs' :
		$mime = 'application/vnd.criticaltools.wbs+xml';
		break;
	case 'pml' :
		$mime = 'application/vnd.ctc-posml';
		break;
	case 'ppd' :
		$mime = 'application/vnd.cups-ppd';
		break;
	case 'curl' :
		$mime = 'application/vnd.curl';
		break;
	case 'rdz' :
		$mime = 'application/vnd.data-vision.rdz';
		break;
	case 'fe_launch' :
		$mime = 'application/vnd.denovo.fcselayout-link';
		break;
	case 'dna' :
		$mime = 'application/vnd.dna';
		break;
	case 'dpg' :
	case 'mwc' :
	case 'dpgraph' :
		$mime = 'application/vnd.dpgraph';
		break;
	case 'dfac' :
		$mime = 'application/vnd.dreamfactory';
		break;
	case 'geo' :
		$mime = 'application/vnd.dynageo';
		break;
	case 'mag' :
		$mime = 'application/vnd.ecowin.chart';
		break;
	case 'nml' :
		$mime = 'application/vnd.enliven';
		break;
	case 'esf' :
		$mime = 'application/vnd.epson.esf';
		break;
	case 'msf' :
		$mime = 'application/vnd.epson.msf';
		break;
	case 'qam' :
		$mime = 'application/vnd.epson.quickanime';
		break;
	case 'slt' :
		$mime = 'application/vnd.epson.salt';
		break;
	case 'ssf' :
		$mime = 'application/vnd.epson.ssf';
		break;
	case 'qcall' :
	case 'qca' :
		$mime = 'application/vnd.ericsson.quickcall';
		break;
	case 'es3' :
	case 'et3' :
		$mime = 'application/vnd.eszigno3+xml';
		break;
	case 'ez2' :
		$mime = 'application/vnd.ezpix-album';
		break;
	case 'ez3' :
		$mime = 'application/vnd.ezpix-package';
		break;
	case 'fdf' :
		$mime = 'application/vnd.fdf';
		break;
	case 'msd' :
	case 'mseed' :
		$mime = 'application/vnd.fdsn.mseed';
		break;
	case 'seed' :
	case 'dataless' :
		$mime = 'application/vnd.fsdn.seed';
		break;
	case 'gph' :
		$mime = 'application/vnd.FloGraphIt';
		break;
	case 'ftc' :
		$mime = 'application/vnd.fluxtime.clip';
		break;
	case 'sfd' :
		$mime = 'application/vnd.font-fontforge-sfd';
		break;
	case 'fm' :
		$mime = 'application/vnd.framemaker';
		break;
	case 'fnc' :
		$mime = 'application/vnd.frogans.fnc';
		break;
	case 'ltf' :
		$mime = 'application/vnd.frogans.ltf';
		break;
	case 'fsc' :
		$mime = 'application/vnd.fsc.weblaunch';
		break;
	case 'oas' :
		$mime = 'application/vnd.fujitsu.oasys';
		break;
	case 'oa2' :
		$mime = 'application/vnd.fujitsu.oasys2';
		break;
	case 'oa3' :
		$mime = 'application/vnd.fujitsu.oasys3';
		break;
	case 'fg5' :
		$mime = 'application/vnd.fujitsu.oasysgp';
		break;
	case 'bh2' :
		$mime = 'application/vnd.fujitsu.oasysprs';
		break;
	case 'ddd' :
		$mime = 'application/vnd.fujixerox.ddd';
		break;
	case 'xdw' :
		$mime = 'application/vnd.fujixerox.docuworks';
		break;
	case 'xbd' :
		$mime = 'application/vnd.fujixerox.docuworks.binder';
		break;
	case 'fzs' :
		$mime = 'application/vnd.fuzzysheet';
		break;
	case 'txd' :
		$mime = 'application/vnd.genomatix.tuxedo';
		break;
	case 'ggb' :
		$mime = 'application/vnd.geogebra.file';
		break;
	case 'ggt' :
		$mime = 'application/vnd.geogebra.tool';
		break;
	case 'gex' :
	case 'gre' :
		$mime = 'application/vnd.geometry-explorer';
		break;
	case 'gxt' :
		$mime = 'application/vnd.geonext';
		break;
	case 'g2w' :
		$mime = 'application/vnd.geoplan';
		break;
	case 'g3w' :
		$mime = 'application/vnd.geospace';
		break;
	case 'kml' :
		$mime = 'application/vnd.google-earth.kml+xml';
		break;
	case 'kmz' :
		$mime = 'application/vnd.google-earth.kmz';
		break;
	case 'gqf' :
	case 'gqs' :
		$mime = 'application/vnd.grafeq';
		break;
	case 'gac' :
		$mime = 'application/vnd.groove-account';
		break;
	case 'ghf' :
		$mime = 'application/vnd.groove-help';
		break;
	case 'gim' :
		$mime = 'application/vnd.groove-identity-message';
		break;
	case 'grv' :
		$mime = 'application/vnd.groove-injector';
		break;
	case 'gtm' :
		$mime = 'application/vnd.groove-tool-message';
		break;
	case 'tpl' :
		$mime = 'application/vnd.groove-tool-template';
		break;
	case 'vcg' :
		$mime = 'application/vnd.groove-vcard';
		break;
	case 'zmm' :
		$mime = 'application/vnd.HandHeld-Entertainment+xml';
		break;
	case 'hbci' :
	case 'hbc' :
	case 'kom' :
	case 'upa' :
	case 'pkd' :
	case 'bpd' :
		$mime = 'application/vnd.hbci';
		break;
	case 'les' :
		$mime = 'application/vnd.hhe.lesson-player';
		break;
	case 'hpgl' :
		$mime = 'application/vnd.hp-HPGL';
		break;
	case 'hpi' :
	case 'hpid' :
		$mime = 'application/vnd.hp-hpid';
		break;
	case 'hps' :
		$mime = 'application/vnd.hp-hps';
		break;
	case 'jlt' :
		$mime = 'application/vnd.hp-jlyt';
		break;
	case 'pcl' :
		$mime = 'application/vnd.hp-PCL';
		break;
	case 'sfd-hdstx' :
		$mime = 'application/vnd.hydrostatix.sof-data';
		break;
	case 'x3d' :
		$mime = 'application/vnd.hzn-3d-crossword';
		break;
	case 'emm' :
		$mime = 'application/vnd.ibm.electronic-media';
		break;
	case 'mpy' :
		$mime = 'application/vnd.ibm.MiniPay';
		break;
	case 'list3820' :
	case 'listafp' :
	case 'afp' :
	case 'pseg3820' :
		$mime = 'application/vnd.ibm.modcap';
		break;
	case 'irm' :
		$mime = 'application/vnd.ibm.rights-management';
		break;
	case 'sc' :
		$mime = 'application/vnd.ibm.secure-container';
		break;
	case 'icc' :
	case 'icm' :
		$mime = 'application/vnd.iccprofile';
		break;
	case 'igl' :
		$mime = 'application/vnd.igloader';
		break;
	case 'ivp' :
		$mime = 'application/vnd.immervision-ivp';
		break;
	case 'ivu' :
		$mime = 'application/vnd.immervision-ivu';
		break;
	case 'xpw' :
	case 'xpx' :
		$mime = 'application/vnd.intercon.formnet';
		break;
	case 'qbo' :
		$mime = 'application/vnd.intu.qbo';
		break;
	case 'qfx' :
		$mime = 'application/vnd.intu.qfx';
		break;
	case 'rcprofile' :
		$mime = 'application/vnd.ipunplugged.rcprofile';
		break;
	case 'irp' :
		$mime = 'application/vnd.irepository.package+xml';
		break;
	case 'xpr' :
		$mime = 'application/vnd.is-xpr';
		break;
	case 'jam' :
		$mime = 'application/vnd.jam';
		break;
	case 'rms' :
		$mime = 'application/vnd.jcp.javame.midlet-rms';
		break;
	case 'jisp' :
		$mime = 'application/vnd.jisp';
		break;
	case 'joda' :
		$mime = 'application/vnd.joost.joda-archive';
		break;
	case 'ktz' :
	case 'ktr' :
		$mime = 'application/vnd.kahootz';
		break;
	case 'karbon' :
		$mime = 'application/vnd.kde.karbon';
		break;
	case 'chrt' :
		$mime = 'application/vnd.kde.kchart';
		break;
	case 'kfo' :
		$mime = 'application/vnd.kde.kformula';
		break;
	case 'flw' :
		$mime = 'application/vnd.kde.kivio';
		break;
	case 'kon' :
		$mime = 'application/vnd.kde.kontour';
		break;
	case 'kpr' :
	case 'kpt' :
		$mime = 'application/vnd.kde.kpresenter';
		break;
	case 'ksp' :
		$mime = 'application/vnd.kde.kspread';
		break;
	case 'kwd' :
	case 'kwt' :
		$mime = 'application/vnd.kde.kword';
		break;
	case 'htke' :
		$mime = 'application/vnd.kenameaapp';
		break;
	case 'kia' :
		$mime = 'application/vnd.kidspiration';
		break;
	case 'kne' :
	case 'knp' :
	case 'sdf' :
		$mime = 'application/vnd.Kinar';
		break;
	case 'skp' :
	case 'skd' :
	case 'skm' :
	case 'skt' :
		$mime = 'application/vnd.koan';
		break;
	case 'sse' :
		$mime = 'application/vnd.kodak-descriptor';
		break;
	case 'lbd' :
		$mime = 'application/vnd.llamagraphics.life-balance.desktop';
		break;
	case 'lbe' :
		$mime = 'application/vnd.llamagraphics.life-balance.exchange+xml';
		break;
	case '123' :
	case 'wk4' :
	case 'wk3' :
	case 'wk1' :
		$mime = 'application/vnd.lotus-1-2-3';
		break;
	case 'apr' :
	case 'vew' :
		$mime = 'application/vnd.lotus-approach';
		break;
	case 'prz' :
	case 'pre' :
		$mime = 'application/vnd.lotus-freelance';
		break;
	case 'nsf' :
	case 'ntf' :
	case 'ndl' :
	case 'ns4' :
	case 'ns3' :
	case 'ns2' :
	case 'nsh' :
	case 'nsg' :
		$mime = 'application/vnd.lotus-notes';
		break;
	case 'or3' :
	case 'or2' :
	case 'org' :
		$mime = 'application/vnd.lotus-organizer';
		break;
	case 'scm' :
		$mime = 'application/vnd.lotus-screencam';
		break;
	case 'lwp' :
	case 'sam' :
		$mime = 'application/vnd.lotus-wordpro';
		break;
	case 'portpkg' :
		$mime = 'application/vnd.macports.portpkg';
		break;
	case 'mdc' :
		$mime = 'application/vnd.marlin.drm.mdcf';
		break;
	case 'mcd' :
		$mime = 'application/vnd.mcd';
		break;
	case 'mc1' :
		$mime = 'application/vnd.medcalcdata';
		break;
	case 'cdkey' :
		$mime = 'application/vnd.mediastation.cdkey';
		break;
	case 'mwf' :
		$mime = 'application/vnd.MFER';
		break;
	case 'mfm' :
		$mime = 'application/vnd.mfmp';
		break;
	case 'flo' :
		$mime = 'application/vnd.micrografx.flo';
		break;
	case 'igx' :
		$mime = 'application/vnd.micrografx.igx';
		break;
	case 'mif' :
		$mime = 'application/vnd.mif';
		break;
	case 'daf' :
		$mime = 'application/vnd.Mobius.DAF';
		break;
	case 'dis' :
		$mime = 'application/vnd.Mobius.DIS';
		break;
	case 'mbk' :
		$mime = 'application/vnd.Mobius.MBK';
		break;
	case 'mqy' :
		$mime = 'application/vnd.Mobius.MQY';
		break;
	case 'msl' :
		$mime = 'application/vnd.Mobius.MSL';
		break;
	case 'plc' :
		$mime = 'application/vnd.Mobius.PLC';
		break;
	case 'txf' :
		$mime = 'application/vnd.Mobius.TXF';
		break;
	case 'mpn' :
		$mime = 'application/vnd.mophun.application';
		break;
	case 'mpc' :
		$mime = 'application/vnd.mophun.certificate';
		break;
	case 'xul' :
		$mime = 'application/vnd.mozilla.xul+xml';
		break;
	case 'cil' :
		$mime = 'application/vnd.ms-artgalry';
		break;
	case 'asf' :
		$mime = 'application/vnd.ms-asf';
		break;
	case 'cab' :
		$mime = 'application/vnd.ms-cab-compressed';
		break;
	case 'xls' :
		$mime = 'application/vnd.ms-excel';
		break;
	case 'eot' :
		$mime = 'application/vnd.ms-fontobject';
		break;
	case 'chm' :
		$mime = 'application/vnd.ms-htmlhelp';
		break;
	case 'ims' :
		$mime = 'application/vnd.ms-ims';
		break;
	case 'lrm' :
		$mime = 'application/vnd.ms-lrm';
		break;
	case 'ppt' :
		$mime = 'application/vnd.ms-powerpoint';
		break;
	case 'mpp' :
		$mime = 'application/vnd.ms-project';
		break;
	case 'tnef' :
	case 'tnf' :
		$mime = 'application/vnd.ms-tnef';
		break;
	case 'wcm' :
	case 'wdb' :
	case 'wks' :
	case 'wps' :
		$mime = 'application/vnd.ms-works';
		break;
	case 'wpl' :
		$mime = 'application/vnd.ms-wpl';
		break;
	case 'xps' :
		$mime = 'application/vnd.ms-xpsdocument';
		break;
	case 'mseq' :
		$mime = 'application/vnd.mseq';
		break;
	case 'crtr' :
		$mime = 'application/vnd.multiad.creator';
		break;
	case 'cif' :
		$mime = 'application/vnd.multiad.creator.cif';
		break;
	case 'mus' :
		$mime = 'application/vnd.musician';
		break;
	case 'msty' :
		$mime = 'application/vnd.muvee.style';
		break;
	case 'entity' :
	case 'request' :
	case 'bkm' :
	case 'kcm' :
		$mime = 'application/vnd.nervana';
		break;
	case 'nlu' :
		$mime = 'application/vnd.neurolanguage.nlu';
		break;
	case 'nnd' :
		$mime = 'application/vnd.noblenet-directory';
		break;
	case 'nns' :
		$mime = 'application/vnd.noblenet-sealer';
		break;
	case 'nnw' :
		$mime = 'application/vnd.noblenet-web';
		break;
	case 'ac' :
		$mime = 'application/vnd.nokia.n-gage.ac+xml';
		break;
	case 'ngdat' :
		$mime = 'application/vnd.nokia.n-gage.data';
		break;
	case 'n-gage' :
		$mime = 'application/vnd.nokia.n-gage.symbian.install';
		break;
	case 'rpst' :
		$mime = 'application/vnd.nokia.radio-preset';
		break;
	case 'rpss' :
		$mime = 'application/vnd.nokia.radio-presets';
		break;
	case 'edm' :
		$mime = 'application/vnd.novadigm.EDM';
		break;
	case 'edx' :
		$mime = 'application/vnd.novadigm.EDX';
		break;
	case 'ext' :
		$mime = 'application/vnd.novadigm.EXT';
		break;
	case 'odc' :
		$mime = 'application/vnd.oasis.opendocument.chart';
		break;
	case 'otc' :
		$mime = 'application/vnd.oasis.opendocument.chart-template';
		break;
	case 'odb' :
		$mime = 'application/vnd.oasis.opendocument.database';
		break;
	case 'odf' :
		$mime = 'application/vnd.oasis.opendocument.formula';
		break;
	case 'otf' :
		$mime = 'application/vnd.oasis.opendocument.formula-template';
		break;
	case 'odg' :
		$mime = 'application/vnd.oasis.opendocument.graphics';
		break;
	case 'otg' :
		$mime = 'application/vnd.oasis.opendocument.graphics-template';
		break;
	case 'odi' :
		$mime = 'application/vnd.oasis.opendocument.image';
		break;
	case 'oti' :
		$mime = 'application/vnd.oasis.opendocument.image-template';
		break;
	case 'odp' :
		$mime = 'application/vnd.oasis.opendocument.presentation';
		break;
	case 'otp' :
		$mime = 'application/vnd.oasis.opendocument.presentation-template';
		break;
	case 'ods' :
		$mime = 'application/vnd.oasis.opendocument.spreadsheet';
		break;
	case 'ots' :
		$mime = 'application/vnd.oasis.opendocument.spreadsheet-template';
		break;
	case 'odt' :
		$mime = 'application/vnd.oasis.opendocument.text';
		break;
	case 'odm' :
		$mime = 'application/vnd.oasis.opendocument.text-master';
		break;
	case 'ott' :
		$mime = 'application/vnd.oasis.opendocument.text-template';
		break;
	case 'oth' :
		$mime = 'application/vnd.oasis.opendocument.text-web';
		break;
	case 'xo' :
		$mime = 'application/vnd.olpc-sugar';
		break;
	case 'dd2' :
		$mime = 'application/vnd.oma.dd2+xml';
		break;
	case 'oxt' :
		$mime = 'application/vnd.openofficeorg.extension';
		break;
	case 'ndc' :
		$mime = 'application/vnd.osa.netdeploy';
		break;
	case 'dp' :
		$mime = 'application/vnd.osgi.dp';
		break;
	case 'prc' :
	case 'pdb' :
	case 'pqa' :
	case 'oprc' :
		$mime = 'application/vnd.palm';
		break;
	case 'str' :
		$mime = 'application/vnd.pg.format';
		break;
	case 'ei6' :
		$mime = 'application/vnd.pg.osasli';
		break;
	case 'pil' :
		$mime = 'application/vnd.piaccess.application-license';
		break;
	case 'efif' :
		$mime = 'application/vnd.picsel';
		break;
	case 'plf' :
		$mime = 'application/vnd.pocketlearn';
		break;
	case 'pbd' :
		$mime = 'application/vnd.powerbuilder6';
		break;
	case 'preminet' :
		$mime = 'application/vnd.preminet';
		break;
	case 'box' :
	case 'vbox' :
		$mime = 'application/vnd.previewsystems.box';
		break;
	case 'mgz' :
		$mime = 'application/vnd.proteus.magazine';
		break;
	case 'qps' :
		$mime = 'application/vnd.publishare-delta-tree';
		break;
	case 'ptid' :
		$mime = 'application/vnd.pvi.ptid1';
		break;
	case 'bar' :
		$mime = 'application/vnd.qualcomm.brew-app-res';
		break;
	case 'qxd' :
	case 'qxt' :
	case 'qwd' :
	case 'qwt' :
	case 'qxl' :
	case 'qxb' :
		$mime = 'application/vnd.Quark.QuarkXPress';
		break;
	case 'bed' :
		$mime = 'application/vnd.realvnc.bed';
		break;
	case 'mxl' :
		$mime = 'application/vnd.recordare.musicxml';
		break;
	case 'link66' :
		$mime = 'application/vnd.route66.link66+xml';
		break;
	case 'st' :
		$mime = 'application/vnd.sailingtracker.track';
		break;
	case 'scd' :
	case 'sla' :
	case 'slaz' :
		$mime = 'application/vnd.scribus';
		break;
	case 's3df' :
		$mime = 'application/vnd.sealed.3df';
		break;
	case 'scsf' :
		$mime = 'application/vnd.sealed.csf';
		break;
	case 'sdoc' :
	case 'sdo' :
	case 's1w' :
		$mime = 'application/vnd.sealed.doc';
		break;
	case 'seml' :
	case 'sem' :
		$mime = 'application/vnd.sealed.eml';
		break;
	case 'smht' :
	case 'smh' :
		$mime = 'application/vnd.sealed.mht';
		break;
	case 'sppt' :
	case 's1p' :
		$mime = 'application/vnd.sealed.ppt';
		break;
	case 'stif' :
		$mime = 'application/vnd.sealed.tiff';
		break;
	case 'sxls' :
	case 'sxl' :
	case 's1e' :
		$mime = 'application/vnd.sealed.xls';
		break;
	case 'stml' :
	case 's1h' :
		$mime = 'application/vnd.sealedmedia.softseal.html';
		break;
	case 'spdf' :
	case 'spd' :
	case 's1a' :
		$mime = 'application/vnd.sealedmedia.softseal.pdf';
		break;
	case 'see' :
		$mime = 'application/vnd.seemail';
		break;
	case 'sema' :
		$mime = 'application/vnd.sema';
		break;
	case 'semd' :
		$mime = 'application/vnd.semd';
		break;
	case 'semf' :
		$mime = 'application/vnd.semf';
		break;
	case 'ifm' :
		$mime = 'application/vnd.shana.informed.formdata';
		break;
	case 'itp' :
		$mime = 'application/vnd.shana.informed.formtemplate';
		break;
	case 'iif' :
		$mime = 'application/vnd.shana.informed.interchange';
		break;
	case 'ipk' :
		$mime = 'application/vnd.shana.informed.package';
		break;
	case 'twd' :
	case 'twds' :
		$mime = 'application/vnd.SimTech-MindMapper';
		break;
	case 'mmf' :
		$mime = 'application/vnd.smaf';
		break;
	case 'teacher' :
		$mime = 'application/vnd.smart.teacher';
		break;
	case 'fo' :
		$mime = 'application/vnd.software602.filler.form+xml';
		break;
	case 'zfo' :
		$mime = 'application/vnd.software602.filler.form-xml-zip';
		break;
	case 'sdkm' :
	case 'sdkd' :
		$mime = 'application/vnd.solent.sdkm+xml';
		break;
	case 'dxp' :
		$mime = 'application/vnd.spotfire.dxp';
		break;
	case 'sfs' :
		$mime = 'application/vnd.spotfire.sfs';
		break;
	case 'wadl' :
		$mime = 'application/vnd.sun.wadl+xml';
		break;
	case 'sus' :
	case 'susp' :
		$mime = 'application/vnd.sus-calendar';
		break;
	case 'bdm' :
		$mime = 'application/vnd.syncml.dm+wbxml';
		break;
	case 'xdm' :
		$mime = 'application/vnd.syncml.dm+xml';
		break;
	case 'xsm' :
		$mime = 'application/vnd.syncml+xml';
		break;
	case 'tao' :
		$mime = 'application/vnd.tao.intent-module-archive';
		break;
	case 'tmo' :
		$mime = 'application/vnd.tmobile-livetv';
		break;
	case 'tpt' :
		$mime = 'application/vnd.trid.tpt';
		break;
	case 'mxs' :
		$mime = 'application/vnd.triscape.mxs';
		break;
	case 'tra' :
		$mime = 'application/vnd.trueapp';
		break;
	case 'ufdl' :
	case 'ufd' :
	case 'frm' :
		$mime = 'application/vnd.ufdl';
		break;
	case 'utz' :
		$mime = 'application/vnd.uiq.theme';
		break;
	case 'umj' :
		$mime = 'application/vnd.umajin';
		break;
	case 'unityweb' :
		$mime = 'application/vnd.unity';
		break;
	case 'uoml' :
	case 'uo' :
		$mime = 'application/vnd.uoml+xml';
		break;
	case 'vcx' :
		$mime = 'application/vnd.vcx';
		break;
	case 'mxi' :
	case 'study-inter' :
	case 'model-inter' :
		$mime = 'application/vnd.vd-study';
		break;
	case 'vwx' :
		$mime = 'application/vnd.vectorworks';
		break;
	case 'vsc' :
		$mime = 'application/vnd.vidsoft.vidconference';
		break;
	case 'vsd' :
	case 'vst' :
	case 'vsw' :
	case 'vss' :
		$mime = 'application/vnd.visio';
		break;
	case 'vis' :
		$mime = 'application/vnd.visionary';
		break;
	case 'vsf' :
		$mime = 'application/vnd.vsf';
		break;
	case 'sic' :
		$mime = 'application/vnd.wap.sic';
		break;
	case 'slc' :
		$mime = 'application/vnd.wap.slc';
		break;
	case 'wbxml' :
		$mime = 'application/vnd.wap.wbxml';
		break;
	case 'wmlc' :
		$mime = 'application/vnd.wap.wmlc';
		break;
	case 'wmlsc' :
		$mime = 'application/vnd.wap.wmlscriptc';
		break;
	case 'wtb' :
		$mime = 'application/vnd.webturbo';
		break;
	case 'wsc' :
		$mime = 'application/vnd.wfa.wsc';
		break;
	case 'wmc' :
		$mime = 'application/vnd.wmc';
		break;
	case 'm' :
		$mime = 'application/vnd.wolfram.mathematica.package';
		break;
	case 'nbp' :
		$mime = 'application/vnd.wolfram.player';
		break;
	case 'wpd' :
		$mime = 'application/vnd.wordperfect';
		break;
	case 'wqd' :
		$mime = 'application/vnd.wqd';
		break;
	case 'stf' :
		$mime = 'application/vnd.wt.stf';
		break;
	case 'wv' :
		$mime = 'application/vnd.wv.csp+wbxml';
		break;
	case 'xar' :
		$mime = 'application/vnd.xara';
		break;
	case 'xfdl' :
	case 'xfd' :
		$mime = 'application/vnd.xfdl';
		break;
	case 'cpkg' :
		$mime = 'application/vnd.xmpie.cpkg';
		break;
	case 'dpkg' :
		$mime = 'application/vnd.xmpie.dpkg';
		break;
	case 'ppkg' :
		$mime = 'application/vnd.xmpie.ppkg';
		break;
	case 'xlim' :
		$mime = 'application/vnd.xmpie.xlim';
		break;
	case 'hvd' :
		$mime = 'application/vnd.yamaha.hv-dic';
		break;
	case 'hvs' :
		$mime = 'application/vnd.yamaha.hv-script';
		break;
	case 'hvp' :
		$mime = 'application/vnd.yamaha.hv-voice';
		break;
	case 'osf' :
		$mime = 'application/vnd.yamaha.openscoreformat';
		break;
	case 'saf' :
		$mime = 'application/vnd.yamaha.smaf-audio';
		break;
	case 'spf' :
		$mime = 'application/vnd.yamaha.smaf-phrase';
		break;
	case 'cmp' :
		$mime = 'application/vnd.yellowriver-custom-menu';
		break;
	case 'zir' :
	case 'zirz' :
		$mime = 'application/vnd.zul';
		break;
	case 'zaz' :
		$mime = 'application/vnd.zzazz.deck+xml';
		break;
	case 'vxml' :
		$mime = 'application/voicexml+xml';
		break;
	case 'wif' :
		$mime = 'application/watcherinfo+xml';
		break;
	case 'wsdl' :
		$mime = 'application/wsdl+xml';
		break;
	case 'wspolicy' :
		$mime = 'application/wspolicy+xml';
		break;
	case 'xav' :
		$mime = 'application/xcap-att+xml';
		break;
	case 'xca' :
		$mime = 'application/xcap-caps+xml';
		break;
	case 'xel' :
		$mime = 'application/xcap-el+xml';
		break;
	case 'xer' :
		$mime = 'application/xcap-error+xml';
		break;
	case 'xns' :
		$mime = 'application/xcap-ns+xml';
		break;
	case 'xhtml' :
	case 'xhtm' :
	case 'xht' :
		$mime = 'application/xhtml+xml';
		break;
	case 'dtd' :
		$mime = 'application/xml-dtd';
		break;
	case 'xop' :
		$mime = 'application/xop+xml';
		break;
	case 'xsl' :
	case 'xslt' :
		$mime = 'application/xslt+xml';
		break;
	case 'mxml' :
	case 'xhvml' :
	case 'xvml' :
	case 'xvm' :
		$mime = 'application/xv+xml';
		break;
	case 'zip' :
		$mime = 'application/zip';
		break;
	case '726' :
		$mime = 'audio/32kadpcm';
		break;
	case 'ac3' :
		$mime = 'audio/ac3';
		break;
	case 'amr' :
		$mime = 'audio/AMR';
		break;
	case 'awb' :
		$mime = 'audio/AMR-WB';
		break;
	case 'aal' :
		$mime = 'audio/ATRAC-ADVANCED-LOSSLESS';
		break;
	case 'atx' :
		$mime = 'audio/ATRAC-X';
		break;
	case 'at3' :
	case 'aa3' :
	case 'omg' :
		$mime = 'audio/ATRAC3';
		break;
	case 'au' :
	case 'snd' :
		$mime = 'audio/basic';
		break;
	case 'dls' :
		$mime = 'audio/dls';
		break;
	case 'evc' :
		$mime = 'audio/EVRC';
		break;
	case 'evb' :
		$mime = 'audio/EVRCB';
		break;
	case 'evw' :
		$mime = 'audio/EVRCWB';
		break;
	case 'lbc' :
		$mime = 'audio/iLBC';
		break;
	case 'l16' :
		$mime = 'audio/L16';
		break;
	case 'mxmf' :
		$mime = 'audio/mobile-xmf';
		break;
	case 'mpga' :
	case 'mp1' :
	case 'mp2' :
	case 'mp3' :
		$mime = 'audio/mpeg';
		break;
	case 'oga' :
	case 'ogg' :
	case 'spx' :
		$mime = 'audio/ogg';
		break;
	case 'sid' :
	case 'psid' :
		$mime = 'audio/prs.sid';
		break;
	case 'qcp' :
		$mime = 'audio/qcelp';
		break;
	case 'smv' :
		$mime = 'audio/SMV';
		break;
	case 'koz' :
		$mime = 'audio/vnd.audikoz';
		break;
	case 'eol' :
		$mime = 'audio/vnd.digital-winds';
		break;
	case 'mlp' :
		$mime = 'audio/vnd.dolby.mlp';
		break;
	case 'dts' :
		$mime = 'audio/vnd.dts';
		break;
	case 'dtshd' :
		$mime = 'audio/vnd.dts.hd';
		break;
	case 'plj' :
		$mime = 'audio/vnd.everad.plj';
		break;
	case 'lvp' :
		$mime = 'audio/vnd.lucent.voice';
		break;
	case 'pya' :
		$mime = 'audio/vnd.ms-playready.media.pya';
		break;
	case 'vbk' :
		$mime = 'audio/vnd.nortel.vbk';
		break;
	case 'ecelp4800' :
		$mime = 'audio/vnd.nuera.ecelp4800';
		break;
	case 'ecelp7470' :
		$mime = 'audio/vnd.nuera.ecelp7470';
		break;
	case 'ecelp9600' :
		$mime = 'audio/vnd.nuera.ecelp9600';
		break;
	case 'smp3' :
	case 'smp' :
	case 's1m' :
		$mime = 'audio/vnd.sealedmedia.softseal.mpeg';
		break;
	case 'fits' :
	case 'fit' :
	case 'fts' :
		$mime = 'image/fits';
		break;
	case 'gif' :
		$mime = 'image/gif';
		break;
	case 'ief' :
		$mime = 'image/ief';
		break;
	case 'jp2' :
	case 'jpg2' :
		$mime = 'image/jp2';
		break;
	case 'jpeg' :
	case 'jpg' :
	case 'jpe' :
	case 'jfif' :
		$mime = 'image/jpeg';
		break;
	case 'jpm' :
	case 'jpgm' :
		$mime = 'image/jpm';
		break;
	case 'jpx' :
	case 'jpf' :
		$mime = 'image/jpx';
		break;
	case 'png' :
		$mime = 'image/png';
		break;
	case 'btif' :
	case 'btf' :
		$mime = 'image/prs.btif';
		break;
	case 'pti' :
		$mime = 'image/prs.pti';
		break;
	case 't38' :
		$mime = 'image/t38';
		break;
	case 'tiff' :
	case 'tif' :
		$mime = 'image/tiff';
		break;
	case 'tfx' :
		$mime = 'image/tiff-fx';
		break;
	case 'psd' :
		$mime = 'image/vnd.adobe.photoshop';
		break;
	case 'djvu' :
	case 'djv' :
		$mime = 'image/vnd.djvu';
		break;
	case 'dxf' :
		$mime = 'image/vnd.dxf';
		break;
	case 'fbs' :
		$mime = 'image/vnd.fastbidsheet';
		break;
	case 'fpx' :
		$mime = 'image/vnd.fpx';
		break;
	case 'fst' :
		$mime = 'image/vnd.fst';
		break;
	case 'mmr' :
		$mime = 'image/vnd.fujixerox.edmics-mmr';
		break;
	case 'rlc' :
		$mime = 'image/vnd.fujixerox.edmics-rlc';
		break;
	case 'pgb' :
		$mime = 'image/vnd.globalgraphics.pgb';
		break;
	case 'ico' :
		$mime = 'image/vnd.microsoft.icon';
		break;
	case 'mdi' :
		$mime = 'image/vnd.ms-modi';
		break;
	case 'hdr' :
	case 'rgbe' :
	case 'xyze' :
		$mime = 'image/vnd.radiance';
		break;
	case 'spng' :
	case 'spn' :
	case 's1n' :
		$mime = 'image/vnd.sealed.png';
		break;
	case 'sgif' :
	case 'sgi' :
	case 's1g' :
		$mime = 'image/vnd.sealedmedia.softseal.gif';
		break;
	case 'sjpg' :
	case 'sjp' :
	case 's1j' :
		$mime = 'image/vnd.sealedmedia.softseal.jpg';
		break;
	case 'wbmp' :
		$mime = 'image/vnd.wap.wbmp';
		break;
	case 'xif' :
		$mime = 'image/vnd.xiff';
		break;
	case 'u8msg' :
		$mime = 'message/global';
		break;
	case 'u8dsn' :
		$mime = 'message/global-delivery-status';
		break;
	case 'u8mdn' :
		$mime = 'message/global-disposition-notification';
		break;
	case 'u8hdr' :
		$mime = 'message/global-headers';
		break;
	case 'eml' :
	case 'mail' :
	case 'art' :
		$mime = 'message/rfc822';
		break;
	case 'igs' :
	case 'iges' :
		$mime = 'model/iges';
		break;
	case 'msh' :
	case 'mesh' :
	case 'silo' :
		$mime = 'model/mesh';
		break;
	case 'dwf' :
		$mime = 'model/vnd.dwf';
		break;
	case 'gdl' :
	case 'gsm' :
	case 'win' :
	case 'dor' :
	case 'lmp' :
	case 'rsm' :
	case 'msm' :
	case 'ism' :
		$mime = 'model/vnd.gdl';
		break;
	case 'gtw' :
		$mime = 'model/vnd.gtw';
		break;
	case 'moml' :
		$mime = 'model/vnd.moml+xml';
		break;
	case 'mts' :
		$mime = 'model/vnd.mts';
		break;
	case 'x_b' :
	case 'xmt_bin' :
		$mime = 'model/vnd.parasolid.transmit.binary';
		break;
	case 'x_t' :
	case 'xmt_txt' :
		$mime = 'model/vnd.parasolid.transmit.text';
		break;
	case 'vtu' :
		$mime = 'model/vnd.vtu';
		break;
	case 'wrl' :
	case 'vrml' :
		$mime = 'model/vrml';
		break;
	case 'vpm' :
		$mime = 'multipart/voice-message';
		break;
	case 'ics' :
	case 'ifb' :
		$mime = 'text/calendar';
		break;
	case 'css' :
		$mime = 'text/css';
		break;
	case 'csv' :
		$mime = 'text/csv';
		break;
	case 'soa' :
	case 'zone' :
		$mime = 'text/dns';
		break;
	case 'html' :
	case 'htm' :
		$mime = 'text/html';
		break;
	case 'js' :
		$mime = 'text/javascript';
		break;
	case 'asc' :
	case 'txt' :
	case 'text' :
	case 'pm' :
	case 'el' :
	case 'c' :
	case 'h' :
	case 'cc' :
	case 'hh' :
	case 'cxx' :
	case 'hxx' :
	case 'f90' :
	case 'ada' :
	case 'sap' :
	case 'awk' :
	case 'conf' :
	case 'cpp' :
	case 'cs' :
	case 'd' :
	case 'diff' :
	case 'dump' :
	case 'e' :
	case 'erl' :
	case 'f' :
	case 'f90' :
	case 'for' :
	case 'gdb' :
	case 'hs' :
	case 'inc' :
	case 'j' :
	case 'java' :
	case 'lisp' :
	case 'jsp' :
	case 'lua' :
	case 'm' :
	case 'q' :
	case 'pas' :
	case 'pl' :
	case 'py' :
	case 'rb' :
	case 's' :
	case 'scheme' :
	case 'sql' :
	case 'spec' :
	case 'vb' :
	case 'vim' :
	case 'xpp' :
	case 'yaml' :
		$mime = 'text/plain';
		break;
	case 'rst' :
		$mime = 'text/prs.fallenstein.rst';
		break;
	case 'tag' :
	case 'dsc' :
		$mime = 'text/prs.lines.tag';
		break;
	case 'rtx' :
		$mime = 'text/richtext';
		break;
	case 'sgml' :
	case 'sgm' :
		$mime = 'text/sgml';
		break;
	case 'tsv' :
		$mime = 'text/tab-separated-values';
		break;
	case 'uris' :
	case 'uri' :
		$mime = 'text/uri-list';
		break;
	case 'abc' :
		$mime = 'text/vnd.abc';
		break;
	case 'dms' :
		$mime = 'text/vnd.DMClientScript';
		break;
	case 'jtd' :
		$mime = 'text/vnd.esmertec.theme-descriptor';
		break;
	case 'fly' :
		$mime = 'text/vnd.fly';
		break;
	case 'flx' :
		$mime = 'text/vnd.fmi.flexstor';
		break;
	case 'gv' :
	case 'dot' :
		$mime = 'text/vnd.graphviz';
		break;
	case '3dml' :
	case '3dm' :
		$mime = 'text/vnd.in3d.3dml';
		break;
	case 'spot' :
	case 'spo' :
		$mime = 'text/vnd.in3d.spot';
		break;
	case 'mpf' :
		$mime = 'text/vnd.ms-mediapackage';
		break;
	case 'ccc' :
		$mime = 'text/vnd.net2phone.commcenter.command';
		break;
	case 'uric' :
		$mime = 'text/vnd.si.uricatalogue';
		break;
	case 'jad' :
		$mime = 'text/vnd.sun.j2me.app-descriptor';
		break;
	case 'ts' :
		$mime = 'text/vnd.trolltech.linguist';
		break;
	case 'si' :
		$mime = 'text/vnd.wap.si';
		break;
	case 'sl' :
		$mime = 'text/vnd.wap.sl';
		break;
	case 'wml' :
		$mime = 'text/vnd.wap.wml';
		break;
	case 'wmls' :
		$mime = 'text/vnd.wap.wmlscript';
		break;
	case 'xml' :
		$mime = 'text/xml';
		break;
	case 'ent' :
		$mime = 'text/xml-external-parsed-entity';
		break;
	case '3gp' :
	case '3gpp' :
		$mime = 'video/3gpp';
		break;
	case '3g2' :
	case '3gpp2' :
		$mime = 'video/3gpp2';
		break;
	case 'mj2' :
	case 'mjp2' :
		$mime = 'video/mj2';
		break;
	case 'mp4' :
	case 'mpg4' :
		$mime = 'video/mp4';
		break;
	case 'mpeg' :
	case 'mpg' :
	case 'mpe' :
		$mime = 'video/mpeg';
		break;
	case 'ogv' :
		$mime = 'video/ogg';
		break;
	case 'qt' :
	case 'mov' :
		$mime = 'video/quicktime';
		break;
	case 'fvt' :
		$mime = 'video/vnd.fvt';
		break;
	case 'mxu' :
	case 'm4u' :
		$mime = 'video/vnd.mpegurl';
		break;
	case 'pyv' :
		$mime = 'video/vnd.ms-playready.media.pyv';
		break;
	case 'nim' :
		$mime = 'video/vnd.nokia.interleaved-multimedia';
		break;
	case 'smpg' :
	case 's11' :
		$mime = 'video/vnd.sealed.mpeg1';
		break;
	case 's14' :
		$mime = 'video/vnd.sealed.mpeg4';
		break;
	case 'sswf' :
	case 'ssw' :
		$mime = 'video/vnd.sealed.swf';
		break;
	case 'smov' :
	case 'smo' :
	case 's1q' :
		$mime = 'video/vnd.sealedmedia.softseal.mov';
		break;
	case 'cpt' :
		$mime = 'application/mac-compactpro';
		break;
	case 'mml' :
		$mime = 'application/mathml+xml';
		break;
	case 'metalink' :
		$mime = 'application/metalink+xml';
		break;
	case 'rss' :
		$mime = 'application/rss+xml';
		break;
	case 'xlam' :
		$mime = 'application/vnd.ms-excel.addin.macroEnabled.12';
		break;
	case 'xlsb' :
		$mime = 'application/vnd.ms-excel.sheet.binary.macroEnabled.12';
		break;
	case 'xlsm' :
		$mime = 'application/vnd.ms-excel.sheet.macroEnabled.12';
		break;
	case 'xltm' :
		$mime = 'application/vnd.ms-excel.template.macroEnabled.12';
		break;
	case 'ppam' :
		$mime = 'application/vnd.ms-powerpoint.addin.macroEnabled.12';
		break;
	case 'pptm' :
		$mime = 'application/vnd.ms-powerpoint.presentation.macroEnabled.12';
		break;
	case 'sldm' :
		$mime = 'application/vnd.ms-powerpoint.slide.macroEnabled.12';
		break;
	case 'ppsm' :
		$mime = 'application/vnd.ms-powerpoint.slideshow.macroEnabled.12';
		break;
	case 'potm' :
		$mime = 'application/vnd.ms-powerpoint.template.macroEnabled.12';
		break;
	case 'docm' :
		$mime = 'application/vnd.ms-word.document.macroEnabled.12';
		break;
	case 'dotm' :
		$mime = 'application/vnd.ms-word.template.macroEnabled.12';
		break;
	case 'dd' :
		$mime = 'application/vnd.oma.dd+xml';
		break;
	case 'dcf' :
		$mime = 'application/vnd.oma.drm.content';
		break;
	case 'o4a' :
	case 'o4v' :
		$mime = 'application/vnd.oma.drm.dcf';
		break;
	case 'dm' :
		$mime = 'application/vnd.oma.drm.message';
		break;
	case 'drc' :
		$mime = 'application/vnd.oma.drm.rights+wbxml';
		break;
	case 'dr' :
		$mime = 'application/vnd.oma.drm.rights+xml';
		break;
	case 'pptx' :
		$mime = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
		break;
	case 'sldx' :
		$mime = 'application/vnd.openxmlformats-officedocument.presentationml.slide';
		break;
	case 'ppsx' :
		$mime = 'application/vnd.openxmlformats-officedocument.presentationml.slideshow';
		break;
	case 'potx' :
		$mime = 'application/vnd.openxmlformats-officedocument.presentationml.template';
		break;
	case 'xlsx' :
		$mime = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
		break;
	case 'xltx' :
		$mime = 'application/vnd.openxmlformats-officedocument.spreadsheetml.template';
		break;
	case 'docx' :
		$mime = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
		break;
	case 'dotx' :
		$mime = 'application/vnd.openxmlformats-officedocument.wordprocessingml.template';
		break;
	case 'sxc' :
		$mime = 'application/vnd.sun.xml.calc';
		break;
	case 'stc' :
		$mime = 'application/vnd.sun.xml.calc.template';
		break;
	case 'sxd' :
		$mime = 'application/vnd.sun.xml.draw';
		break;
	case 'std' :
		$mime = 'application/vnd.sun.xml.draw.template';
		break;
	case 'sxi' :
		$mime = 'application/vnd.sun.xml.impress';
		break;
	case 'sti' :
		$mime = 'application/vnd.sun.xml.impress.template';
		break;
	case 'sxm' :
		$mime = 'application/vnd.sun.xml.math';
		break;
	case 'sxw' :
		$mime = 'application/vnd.sun.xml.writer';
		break;
	case 'sxg' :
		$mime = 'application/vnd.sun.xml.writer.global';
		break;
	case 'stw' :
		$mime = 'application/vnd.sun.xml.writer.template';
		break;
	case 'sis' :
		$mime = 'application/vnd.symbian.install';
		break;
	case 'mms' :
		$mime = 'application/vnd.wap.mms-message';
		break;
	case 'bcpio' :
		$mime = 'application/x-bcpio';
		break;
	case 'torrent' :
		$mime = 'application/x-bittorrent';
		break;
	case 'bz2' :
		$mime = 'application/x-bzip2';
		break;
	case 'vcd' :
		$mime = 'application/x-cdlink';
		break;
	case 'pgn' :
		$mime = 'application/x-chess-pgn';
		break;
	case 'cpio' :
		$mime = 'application/x-cpio';
		break;
	case 'csh' :
		$mime = 'application/x-csh';
		break;
	case 'dcr' :
	case 'dir' :
	case 'dxr' :
		$mime = 'application/x-director';
		break;
	case 'dvi' :
		$mime = 'application/x-dvi';
		break;
	case 'spl' :
		$mime = 'application/x-futuresplash';
		break;
	case 'gtar' :
		$mime = 'application/x-gtar';
		break;
	case 'gz' :
	case 'tgz' :
		$mime = 'application/x-gzip';
		break;
	case 'hdf' :
		$mime = 'application/x-hdf';
		break;
	case 'jar' :
		$mime = 'application/x-java-archive';
		break;
	case 'jnlp' :
		$mime = 'application/x-java-jnlp-file';
		break;
	case 'pack' :
		$mime = 'application/x-java-pack200';
		break;
	case 'kil' :
		$mime = 'application/x-killustrator';
		break;
	case 'latex' :
		$mime = 'application/x-latex';
		break;
	case 'nc' :
	case 'cdf' :
		$mime = 'application/x-netcdf';
		break;
	case 'pl' :
		$mime = 'application/x-perl';
		break;
	case 'rpm' :
		$mime = 'application/x-rpm';
		break;
	case 'sh' :
	case 'bash' :
		$mime = 'application/x-sh';
		break;
	case 'shar' :
		$mime = 'application/x-shar';
		break;
	case 'swf' :
		$mime = 'application/x-shockwave-flash';
		break;
	case 'sit' :
		$mime = 'application/x-stuffit';
		break;
	case 'sv4cpio' :
		$mime = 'application/x-sv4cpio';
		break;
	case 'sv4crc' :
		$mime = 'application/x-sv4crc';
		break;
	case 'tar' :
		$mime = 'application/x-tar';
		break;
	case 'tcl' :
		$mime = 'application/x-tcl';
		break;
	case 'tex' :
		$mime = 'application/x-tex';
		break;
	case 'texinfo' :
	case 'texi' :
		$mime = 'application/x-texinfo';
		break;
	case 't' :
	case 'tr' :
	case 'roff' :
		$mime = 'application/x-troff';
		break;
	case 'man' :
	case '1' :
	case '2' :
	case '3' :
	case '4' :
	case '5' :
	case '6' :
	case '7' :
	case '8' :
		$mime = 'application/x-troff-man';
		break;
	case 'me' :
		$mime = 'application/x-troff-me';
		break;
	case 'ms' :
		$mime = 'application/x-troff-ms';
		break;
	case 'ustar' :
		$mime = 'application/x-ustar';
		break;
	case 'src' :
		$mime = 'application/x-wais-source';
		break;
	case 'xz' :
		$mime = 'application/x-xz';
		break;
	case 'mid' :
	case 'midi' :
	case 'kar' :
		$mime = 'audio/midi';
		break;
	case 'aif' :
	case 'aiff' :
	case 'aifc' :
		$mime = 'audio/x-aiff';
		break;
	case 'mod' :
	case 'ult' :
	case 'uni' :
	case 'm15' :
	case 'mtm' :
	case '669' :
	case 'med' :
		$mime = 'audio/x-mod';
		break;
	case 'm3u' :
		$mime = 'audio/x-mpegurl';
		break;
	case 'wax' :
		$mime = 'audio/x-ms-wax';
		break;
	case 'wma' :
		$mime = 'audio/x-ms-wma';
		break;
	case 'ram' :
	case 'rm' :
		$mime = 'audio/x-pn-realaudio';
		break;
	case 'ra' :
		$mime = 'audio/x-realaudio';
		break;
	case 's3m' :
		$mime = 'audio/x-s3m';
		break;
	case 'stm' :
		$mime = 'audio/x-stm';
		break;
	case 'wav' :
		$mime = 'audio/x-wav';
		break;
	case 'xyz' :
		$mime = 'chemical/x-xyz';
		break;
	case 'bmp' :
		$mime = 'image/bmp';
		break;
	case 'svg' :
	case 'svgz' :
		$mime = 'image/svg+xml';
		break;
	case 'ras' :
		$mime = 'image/x-cmu-raster';
		break;
	case 'pnm' :
		$mime = 'image/x-portable-anymap';
		break;
	case 'pbm' :
		$mime = 'image/x-portable-bitmap';
		break;
	case 'pgm' :
		$mime = 'image/x-portable-graymap';
		break;
	case 'ppm' :
		$mime = 'image/x-portable-pixmap';
		break;
	case 'rgb' :
		$mime = 'image/x-rgb';
		break;
	case 'tga' :
		$mime = 'image/x-targa';
		break;
	case 'xbm' :
		$mime = 'image/x-xbitmap';
		break;
	case 'xpm' :
		$mime = 'image/x-xpixmap';
		break;
	case 'xwd' :
		$mime = 'image/x-xwindowdump';
		break;
	case 'manifest' :
		$mime = 'text/cache-manifest';
		break;
	case 'pod' :
		$mime = 'text/x-pod';
		break;
	case 'etx' :
		$mime = 'text/x-setext';
		break;
	case 'vcf' :
		$mime = 'text/x-vcard';
		break;
	case 'webm' :
		$mime = 'video/webm';
		break;
	case 'flv' :
		$mime = 'video/x-flv';
		break;
	case 'asx' :
		$mime = 'video/x-ms-asf';
		break;
	case 'wm' :
		$mime = 'video/x-ms-wm';
		break;
	case 'wmv' :
		$mime = 'video/x-ms-wmv';
		break;
	case 'wmx' :
		$mime = 'video/x-ms-wmx';
		break;
	case 'wvx' :
		$mime = 'video/x-ms-wvx';
		break;
	case 'avi' :
		$mime = 'video/x-msvideo';
		break;
	case 'movie' :
		$mime = 'video/x-sgi-movie';
		break;
	case 'ice' :
		$mime = 'x-conference/x-cooltalk';
		break;
	case 'sisx' :
		$mime = 'x-epoc/x-sisx-app';
		break;
	case 'php' :
		$mime = 'application/x-httpd-php';
		break;
	case 'phps' :
		$mime = 'application/x-httpd-php-source';
		break;
	default:
		$mime = 'application/octet-stream';
}
?>
